import type { Metadata } from "next";
import { Krub, Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const krub = Krub({
  variable: "--font-krub",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="sr-RS"
      className={cn("antialiased", krub.variable, geist.variable, "font-sans")}
    >
      <body>
        <div className="bg-[#121212] text-mt450-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
